version: "3"
services:

  service:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: react_blog:service
    ports:
      - 9000:9002
    restart: on-failure
    depends_on:
      - db
    #environment:
    #  MYSQL_HOST: host.docker.internal # 此处 localhost 换为 mysql 容器名，在同一个自定义网络下，变会自动解析为 IP 连接
    #  MYSQL_PORT: 3306
    #  MYSQL_USER: root
    #  MYSQL_PASSWORD: 123456
    volumes:
      - ../article:/usr/src/app/article
    #network_mode: host
    container_name: react_blog_service
    networks:
      - react_network
    
  db:
    image: mysql
    ports:
      - 33061:3306
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: react_blog
    container_name: react_blog_mysql
    networks:
      - react_network
networks:
  react_network: